### PR TITLE
5.1: Token Editor Improvements

### LINKED ISSUE #200: Improve gateway admin token editor UX
A number of improvements could be made to the admin token editor to keep the user more informed API problems and missing information.

### Potential Improvements

 - [x] Add JS notices for gateway API results
    - [ ] Remove Token - If API deletion fails (invalid token, etc...), add a notice and offer to remove the meta entry anyway
    - [ ] Get Tokens - Notice if failed to retrieve tokens, offer refresh
 - [x] Hide the token tables if the gateway requires customer ID but none is set
 - [x] Attempt to retrieve tokens when a customer ID is set/changed
 - [ ] Optional token ID links to a gateway's external URL for management if supported

Based on feedback from https://github.com/woocommerce/woocommerce-gateway-paypal-powered-by-braintree/pull/162#issuecomment-287921426

### Questions to Consider

- Should the purpose of the editor be to allow admins to manage customer payment methods fully (retrieve/update/remove via API), or purely to manage/fix _stored meta_?

### PR DESCRIPTION
**Pull request by ChaseWiseman**
Closes #200

### CODE REVIEW

File: woocommerce/payment-gateway/assets/js/admin/sv-wc-payment-gateway-token-editor.coffee [hunk 1]
```diff
@@ -27,37 +27,47 @@ jQuery( document ).ready ($) ->
...
+
+				return handleError( editor, response.data ) unless response.success
 
-			row = $( this ).closest( 'tr' )
+				$( row ).remove()
 
-			# If this is an unsaved token, just remove the row
-			if ( row.hasClass( 'new-token' ) )
+				# no more tokens? Display a message
+				if ( editor.find( 'tr.token' ).length == 0 )
```
Comment (ragulka) [inline woocommerce/payment-gateway/assets/js/admin/sv-wc-payment-gateway-token-editor.coffee]: `is` is preferred over `==` as per https://github.com/polarmobile/coffeescript-style-guide/blob/master/README.md
